// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh4SeqnswZKJnufxawnLYE7GTNZZIKJAQ',
    appId: '1:706759637846:web:e886a5b854e282d57eb4f7',
    messagingSenderId: '706759637846',
    projectId: 'chat-1f25f',
    authDomain: 'chat-1f25f.firebaseapp.com',
    storageBucket: 'chat-1f25f.appspot.com',
    measurementId: 'G-TD5WYBB77C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrCo3Kx-XJ4v4qSux3tQHc0rggaliN2uE',
    appId: '1:706759637846:android:b8bf785b66d93fe97eb4f7',
    messagingSenderId: '706759637846',
    projectId: 'chat-1f25f',
    storageBucket: 'chat-1f25f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWYjLZdpedM2_dkXNh1yMgb2W_dNKBAPk',
    appId: '1:706759637846:ios:9430f7ccffe475567eb4f7',
    messagingSenderId: '706759637846',
    projectId: 'chat-1f25f',
    storageBucket: 'chat-1f25f.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWYjLZdpedM2_dkXNh1yMgb2W_dNKBAPk',
    appId: '1:706759637846:ios:97684b58b4f40a3a7eb4f7',
    messagingSenderId: '706759637846',
    projectId: 'chat-1f25f',
    storageBucket: 'chat-1f25f.appspot.com',
    iosBundleId: 'com.example.chat.RunnerTests',
  );
}
